name: Type checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tsc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run type-checking
        run: npm run ci:tsc
